# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: cicd-pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: docker version
        run: docker --version

      - name: dockerhub login
        run: docker login

      - name: docker build
        run: docker build -t rezaul0168/shopnow-client:v1 shopnow-client/

      - name: docker push
        run: docker push rezaul0168/shopnow-client:v1
